import 'package:instagram_clone/models/user_post_model.dart';

List<UserPost> postsStorage = [
  UserPost("zarifaka", ["assets/images/third_avatar.jpeg"], 0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
  UserPost("zarifaka", ["assets/images/third_avatar.jpeg"], 0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
  UserPost("zarifaka", ["assets/images/third_avatar.jpeg"], 0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
  UserPost("zarifaka", ["assets/images/third_avatar.jpeg"], 0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
  UserPost("zarifaka", ["assets/images/third_avatar.jpeg"], 0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
  UserPost("her_Aslanov", ["assets/images/third_avatar.jpeg"], 0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
  UserPost("shakhnoza_ibragimova", ["assets/images/third_avatar.jpeg"], 0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
  UserPost("iSystem_learning_center", ["assets/images/third_avatar.jpeg"], 0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
  UserPost("vuejs_uzbekistan", ["assets/images/third_avatar.jpeg"], 0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
  UserPost("nodejs_uzbekistan", ["assets/images/third_avatar.jpeg"], 0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
  UserPost("python_uzbekistan", ["assets/images/third_avatar.jpeg"], 0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
  UserPost("Abduqayum", ["assets/images/third_avatar.jpeg"], 0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
  UserPost(
      "Cambridge International University",
      ["assets/images/third_avatar.jpeg"],
      0,
      "Assalamu alaykum hurmatli robotiks lab o'quvchilari va abuturientlari. Nima gap silani yanig kursimizga taklif qilamiz. Karuchi kursni biri, c++ da algaritmlash karochi. Bilsela bilarsila, darsni kaminani o'zi o'tadi. Yengil telefon qilib ro'yxatdan o'tovrasila. Sila bilan Zarif brat"),
];
